name: Build Windows Release

on:
  push:

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cryptography

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --onefile dev_webserver.py --name debserv --icon Icon.ico

      - name: Prepare release package
        shell: pwsh
        run: |
          $packageDir = "release-package"
          New-Item $packageDir -ItemType Directory -Force | Out-Null
          Copy-Item -Path "dist/debserv.exe" -Destination $packageDir -Force
          Copy-Item -Path "config.json" -Destination $packageDir -Force
          Copy-Item -Path "Certs" -Destination $packageDir -Recurse -Force
          Copy-Item -Path "www" -Destination $packageDir -Recurse -Force
          $items = Get-ChildItem $packageDir
          Compress-Archive -Path $items.FullName -DestinationPath "debserv.zip" -Force

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: Automated build ${{ github.run_number }}
          files: debserv.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
